services:
  - type: web
    name: veritas-ai
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: MODEL_PROVIDER
        value: groq
      - key: MODEL_NAME
        value: openai/gpt-oss-20b
      - key: SUMMARIZATION_MODEL
        value: openai/gpt-oss-20b
      - key: GROQ_API_KEY
        sync: false
      - key: SEARCH_PROVIDER
        value: tavily
      - key: TAVILY_API_KEY
        sync: false
